apiVersion: v1
kind: ConfigMap
metadata:
  name: proyecto2-config
  namespace: mlops-proyecto2
data:
  POSTGRES_HOST: postgres
  POSTGRES_PORT: "5432"
  DATA_DB: mlops_data
  MLFLOW_DB: mlflow_meta
  AIRFLOW_DB: airflow_meta
  MLFLOW_TRACKING_URI: http://mlflow:5000
  MLFLOW_MODEL_NAME: DiabetesReadmissionModel
  MLFLOW_MODEL_ALIAS: champion
  MLFLOW_S3_ENDPOINT_URL: http://minio:9000
  MINIO_BUCKET: mlflow-artifacts
  DATASET_URL: https://docs.google.com/uc?export=download&id=1k5-1caezQ3zWJbKaiMULTGq-3sz6uThC
  DATASET_PATH: /opt/project/data/Diabetes.csv
  TARGET_COLUMN: readmitted
  BATCH_SIZE: "15000"
  API_URL: http://api:8000
  AIRFLOW__CORE__EXECUTOR: LocalExecutor
  AIRFLOW__CORE__LOAD_EXAMPLES: "False"
  AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: "True"
  AIRFLOW__WEBSERVER__EXPOSE_CONFIG: "True"
  AIRFLOW__API__AUTH_BACKENDS: airflow.api.auth.backend.basic_auth
  AIRFLOW_UID: "50000"
---
apiVersion: v1
kind: Secret
metadata:
  name: proyecto2-secrets
  namespace: mlops-proyecto2
type: Opaque
stringData:
  POSTGRES_USER: mlops
  POSTGRES_PASSWORD: mlops123
  AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://mlops:mlops123@postgres:5432/airflow_meta
  MINIO_ROOT_USER: minioadmin
  MINIO_ROOT_PASSWORD: minioadmin123
  AWS_ACCESS_KEY_ID: minioadmin
  AWS_SECRET_ACCESS_KEY: minioadmin123
  AIRFLOW__CORE__FERNET_KEY: 7fF7uxS4DUJ28u5GkgGN1RCjSc5MiNmiY6L0H944sWg=
  AIRFLOW_ADMIN_USERNAME: admin
  AIRFLOW_ADMIN_PASSWORD: admin123
