apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mlops-proyecto-final
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/johanemiliopaez/MLOPS_PUJ.git
    targetRevision: main
    path: mlops_proyecto-final/k8s
    kustomize: {}
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
