apiVersion: v1
kind: PersistentVolumeClaim
metadata: { name: airflow-logs-pvc }
spec:
  accessModes: ["ReadWriteOnce"]
  resources: { requests: { storage: 2Gi } }
---
apiVersion: apps/v1
kind: Deployment
metadata: { name: airflow-scheduler }
spec:
  replicas: 1
  selector: { matchLabels: { app: airflow-scheduler } }
  template:
    metadata: { labels: { app: airflow-scheduler } }
    spec:
      initContainers:
      - name: fix-logs-permissions
        image: busybox
        command: ["sh", "-c", "chmod -R 777 /opt/airflow/logs"]
        volumeMounts: [{ mountPath: /opt/airflow/logs, name: airflow-logs }]
      containers:
      - name: scheduler
        image: puenayan1/mlops-realestate-airflow:v1
        command: ["airflow", "scheduler"]
        envFrom: [{ configMapRef: { name: mlops-config } }, { secretRef: { name: mlops-secrets } }]
        env: [{ name: AIRFLOW__DATABASE__SQL_ALCHEMY_CONN, valueFrom: { secretKeyRef: { name: mlops-secrets, key: AIRFLOW_DB_URI } } }]
        volumeMounts: [{ mountPath: /opt/airflow/logs, name: airflow-logs }]
      volumes:
      - name: airflow-logs
        persistentVolumeClaim: { claimName: airflow-logs-pvc }
---
apiVersion: apps/v1
kind: Deployment
metadata: { name: airflow-webserver }
spec:
  replicas: 1
  selector: { matchLabels: { app: airflow-webserver } }
  template:
    metadata: { labels: { app: airflow-webserver } }
    spec:
      initContainers:
      - name: fix-logs-permissions
        image: busybox
        command: ["sh", "-c", "chmod -R 777 /opt/airflow/logs"]
        volumeMounts: [{ mountPath: /opt/airflow/logs, name: airflow-logs }]
      - name: airflow-db-init
        image: puenayan1/mlops-realestate-airflow:v1
        command: ["airflow", "db", "upgrade"]
        envFrom: [{ configMapRef: { name: mlops-config } }, { secretRef: { name: mlops-secrets } }]
        env: [{ name: AIRFLOW__DATABASE__SQL_ALCHEMY_CONN, valueFrom: { secretKeyRef: { name: mlops-secrets, key: AIRFLOW_DB_URI } } }]
      - name: airflow-user-create
        image: puenayan1/mlops-realestate-airflow:v1
        command: ["bash", "-c", "airflow users create -r Admin -u admin -p admin -e admin@example.com -f admin -l admin || true"]
        envFrom: [{ configMapRef: { name: mlops-config } }, { secretRef: { name: mlops-secrets } }]
        env: [{ name: AIRFLOW__DATABASE__SQL_ALCHEMY_CONN, valueFrom: { secretKeyRef: { name: mlops-secrets, key: AIRFLOW_DB_URI } } }]
      containers:
      - name: webserver
        image: puenayan1/mlops-realestate-airflow:v1
        command: ["airflow", "webserver"]
        ports: [{ containerPort: 8080 }]
        envFrom: [{ configMapRef: { name: mlops-config } }, { secretRef: { name: mlops-secrets } }]
        env: [{ name: AIRFLOW__DATABASE__SQL_ALCHEMY_CONN, valueFrom: { secretKeyRef: { name: mlops-secrets, key: AIRFLOW_DB_URI } } }]
        volumeMounts: [{ mountPath: /opt/airflow/logs, name: airflow-logs }]
      volumes:
      - name: airflow-logs
        persistentVolumeClaim: { claimName: airflow-logs-pvc }
---
apiVersion: v1
kind: Service
metadata: { name: airflow-webserver }
spec:
  type: LoadBalancer
  selector: { app: airflow-webserver }
  ports: [{ port: 8080 }]